---

- hosts:all
  become: true
  tasks:
  
  - name: update repository:
    apt:
      update_cache: yes
      when: ansible_distribution == "Ubuntu" //when it is a diffrent OS 

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
      when: ansible_distribution == "Ubuntu"

